DAST fixing

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -115,8 +115,19 @@ jobs:
 
       - name: Wait for App to be ready
         run: |
-          timeout 60s sh -c 'until curl -s localhost:8000; do sleep 5; done'
-
+          echo "Waiting for Django to respond..."
+          for i in {1..20}; do
+            if curl -s -o /dev/null -w "%{http_code}" localhost:8000 | grep "200\|301\|302\|404" > /dev/null; then
+              echo "App is up!"
+              exit 0
+            fi
+            echo "Attempt $i: App not ready yet. Sleeping 5s..."
+            docker ps # Pokaż czy kontener w ogóle żyje
+            sleep 5
+          done
+          echo "App failed to start in time."
+          docker logs django-app
+          exit 1
       - name: ZAP Scan
         uses: zaproxy/action-baseline@v0.12.0
         with:
